### ISSUE TITLE
analysis of .cxd files not working under Linux

### ISSUE THREAD

**Issue by efronhofer** [pennekampster/bemovi#36]
The analysis of .cxd files is not working out-of-the box under Linux. This problem occurs because in the relevant functions the path to the ImageJ plugin directory (for using the required Bio-formats plugin) is hard coded to "/Applications/ImageJ" for all unix systems. However, this specific path is only correct for Mac OS. What we need here is a part of the "IJ.path" path (without "ij.jar"). Couldn't we use this information to make bemovi also work for .cxd files under Linux? NOTE: This will be really relevant if we want to use the MOSAIC plugin instead of the standalone particle tracker.

**Comment by pennekampster** [comment]
Seems you identified the problem and know a solution. I will not have the time to fix this myself soon, best would be to clone the repo, replace the hard coded paths by a relative path (e.g. paste(IJ.path, "/plugins") ), test and send a pull request! Become a BEMOVI contributor ;) otherwise I will look into it as soon as I find time!

**Comment by pennekampster** [comment]
Hi @efronhofer, the hardcoded path was resolved. Can you check that the fix works under Linux? Many thanks!
